name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "17 6 * * 1"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: ShellCheck
        run: shellcheck gofile tests/*.sh
      - name: Tests from Bash
        run: ./tests/test_gofile.sh
      - name: Install Zsh
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: Tests from Zsh
        shell: zsh {0}
        run: ./tests/test_gofile.sh
